### ISSUE TITLE
As a user, i want trinity-neo-gui work as a full Trinity node

### ISSUE THREAD

**Issue by pigxo** [trinity-project/trinity-neo-gui#3]
trinity-neo-gui  should be a full Trinity node
can connect to the Trinity network via trinity-neo-gui
can obtain Trinity network symbol, trinity uri
can support neo, gas, and any other nep5 tokens
can support the full rtrinity protocol
can do transaction with any other Trinity node

**Comment by yilwhust** [comment]
Have implemented all function
