### ISSUE TITLE
As a user, i want trinity-neo-gui has channel management functions

### ISSUE THREAD

**Issue by pigxo** [trinity-project/trinity-neo-gui#6]
user can check the channel status
user can get the channel transaction history
user can select channel via peer node name
user can select channel via channel state
user can select channel via peer channel banlance

**Comment by yilwhust** [comment]
Have implemented the US

**Comment by yilwhust** [comment]
Have supported all function about the US

**Comment by yilwhust** [comment]
Have implemented the US
