### ISSUE TITLE
Question about trinity-neo-gui

### ISSUE THREAD

**Issue by namnhfreelancer** [trinity-project/trinity-neo-gui#9]
Hello, i have some question. 
This version trinity-neo-gui in future will official release in Neo Official Github or only in Trinity Github ?

**Comment by biubiubird** [comment]
> Hello, i have some question.
> This version trinity-neo-gui in future will official release in Neo Official Github or only in Trinity Github ?

Hi. We are going to publish trinity-neo-gui in our repo at first, and then pull request to neo-gui repo. After their audit, the final product will be merged into their repo. Of course we will have it here as well.
